### ISSUE TITLE
How do I uninstall this?

### ISSUE THREAD

**Issue by Silvergish** [bashonly/yt-dlp-TTUser#12]
I installed using `python3 -m pip install -U https://github.com/bashonly/yt-dlp-TTUser/archive/master.zip`

It's not working for me. How do I uninstall this?

Thank you.

**Comment by bashonly** [comment]
```
python3 -m pip uninstall yt-dlp-TTUser
```

If you are using the exe, I'd suggest installing the plugin using the wheel (`.whl` file) from the releases page

**Comment by Silvergish** [comment]
Thank you so much. That worked.
