### ISSUE TITLE
How to remove watermarks?

### ISSUE THREAD

**Issue by AAndyProgram** [bashonly/yt-dlp-TTUser#13]
I'm currently using version [2024.02.27](https://github.com/bashonly/yt-dlp-TTUser/releases/tag/2024.02.27). Previous versions downloaded videos without watermarks. Now downloaded with watermarks.

**Comment by bashonly** [comment]
It has been fixed in yt-dlp master/nightly. I'd also recommend upgrading to version 2024.03.18 of the plugin

**Comment by AAndyProgram** [comment]
Thank you!
