### ISSUE TITLE
Update Support for Tiktok downloading user channel please

### ISSUE THREAD

**Issue by Zachary247** [bashonly/yt-dlp-TTUser#3]
Same Problem as yt-dlp its failing to download videos. I think Error trying to parse the JSON data from the TikTok user video list page. It was working 2 days ago just fine on yt-dlp but it seems tiktok have updated there website recently and this plugin doesnt help solve it.

Complete Verbose Output
PS D:\yt-dlp-TTUser> .\yt-dlp --extractor-args "tiktok:sec_uid=7275274545622336513" -vU https://www.tiktok.com/@cblackyyy
[debug] Command-line config: ['--extractor-args', 'tiktok:sec_uid=7275274545622336513', '-vU', 'https://www.tiktok.com/@cblackyyy']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@cblackyyy
[tiktok:user] cblackyyy: Downloading webpage
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
ERROR: [tiktok:user] cblackyyy: cblackyyy: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\tiktok.py", line 806, in _real_extract
  File "yt_dlp\utils\traversal.py", line 239, in traverse_obj
  File "yt_dlp\utils\traversal.py", line 227, in _traverse_obj
  File "yt_dlp\utils\traversal.py", line 215, in apply_path
  File "yt_dlp\utils\traversal.py", line 173, in apply_key
  File "yt_dlp\utils\_utils.py", line 2195, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 774, in _video_entries_api
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\extractor\common.py", line 3760, in _error_or_warning
  File "yt_dlp\utils\_utils.py", line 5122, in report_retry
  File "yt_dlp\extractor\tiktok.py", line 776, in _video_entries_api
  File "yt_dlp\extractor\tiktok.py", line 132, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 125, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 62, in _call_api_impl
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 1039, in download_handle
  File "yt_dlp\extractor\common.py", line 1029, in parse
  File "yt_dlp\extractor\common.py", line 1016, in _parse_json
  File "yt_dlp\extractor\common.py", line 999, in __print_error

  File "yt_dlp\utils\_utils.py", line 555, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1013, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 563, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

**Comment by bashonly** [comment]
You haven't installed the plugin correctly. It is not being loaded by yt-dlp in the above log. The plugin will not be loaded by yt-dlp if you just downloaded/installed it to `D:\yt-dlp-TTUser`

See https://github.com/bashonly/yt-dlp-TTUser#installation for instructions on how to install it with pip,
or see https://github.com/yt-dlp/yt-dlp#installing-plugins for other installation methods.

**Comment by Zachary247** [comment]
I tried following  C:\Users\zacha\AppData\yt-dlp\plugins\extractor\yt_dlp_plugins\tt_user.py and I tried the same command in powershell and it didn't work what did I do wrong? 
PS D:\yt-dlp>  .\yt-dlp --extractor-args "tiktok:sec_uid=7275926590302995458" -vU https://www.tiktok.com/@chucker03
[debug] Command-line config: ['--extractor-args', 'tiktok:sec_uid=7275926590302995458', '-vU', 'https://www.tiktok.com/@chucker03']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@chucker03
[tiktok:user] chucker03: Downloading webpage
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
ERROR: [tiktok:user] chucker03: chucker03: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\tiktok.py", line 806, in _real_extract
  File "yt_dlp\utils\traversal.py", line 239, in traverse_obj
  File "yt_dlp\utils\traversal.py", line 227, in _traverse_obj
  File "yt_dlp\utils\traversal.py", line 215, in apply_path
  File "yt_dlp\utils\traversal.py", line 173, in apply_key
  File "yt_dlp\utils\_utils.py", line 2195, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 774, in _video_entries_api
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\extractor\common.py", line 3760, in _error_or_warning
  File "yt_dlp\utils\_utils.py", line 5122, in report_retry
  File "yt_dlp\extractor\tiktok.py", line 776, in _video_entries_api
  File "yt_dlp\extractor\tiktok.py", line 132, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 125, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 62, in _call_api_impl
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 1039, in download_handle
  File "yt_dlp\extractor\common.py", line 1029, in parse
  File "yt_dlp\extractor\common.py", line 1016, in _parse_json
  File "yt_dlp\extractor\common.py", line 999, in __print_error

  File "yt_dlp\utils\_utils.py", line 555, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1013, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 563, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

**Comment by bashonly** [comment]
> `C:\Users\zacha\AppData\yt-dlp\plugins\extractor\yt_dlp_plugins\tt_user.py`

inside the `yt-dlp\plugins` folder you need to create a package folder, e.g. `yt-dlp-TTUser`

so the path should look like this:
`C:\Users\zacha\AppData\yt-dlp\plugins\yt-dlp-TTUser\extractor\yt_dlp_plugins\tt_user.py`

**Comment by Zachary247** [comment]
C:\Users\zacha\AppData\yt-dlp\plugins\yt-dlp-TTUser\extractor\yt_dlp_plugins\tt_user.py
 I did that but Its still the same results :/
PS D:\yt-dlp>  .\yt-dlp --extractor-args "tiktok:sec_uid=7275926590302995458" -vU https://www.tiktok.com/@chucker03
[debug] Command-line config: ['--extractor-args', 'tiktok:sec_uid=7275926590302995458', '-vU', 'https://www.tiktok.com/@chucker03']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@chucker03
[tiktok:user] chucker03: Downloading webpage
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
ERROR: [tiktok:user] chucker03: chucker03: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\tiktok.py", line 806, in _real_extract
  File "yt_dlp\utils\traversal.py", line 239, in traverse_obj
  File "yt_dlp\utils\traversal.py", line 227, in _traverse_obj
  File "yt_dlp\utils\traversal.py", line 215, in apply_path
  File "yt_dlp\utils\traversal.py", line 173, in apply_key
  File "yt_dlp\utils\_utils.py", line 2195, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 774, in _video_entries_api
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\extractor\common.py", line 3760, in _error_or_warning
  File "yt_dlp\utils\_utils.py", line 5122, in report_retry
  File "yt_dlp\extractor\tiktok.py", line 776, in _video_entries_api
  File "yt_dlp\extractor\tiktok.py", line 132, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 125, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 62, in _call_api_impl
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 1039, in download_handle
  File "yt_dlp\extractor\common.py", line 1029, in parse
  File "yt_dlp\extractor\common.py", line 1016, in _parse_json
  File "yt_dlp\extractor\common.py", line 999, in __print_error

  File "yt_dlp\utils\_utils.py", line 555, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1013, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 563, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

**Comment by bashonly** [comment]
ah my bad it should be `AppData\Roaming\yt-dlp`...

**Comment by Zachary247** [comment]
C:\Users\zacha\AppData\Roaming\yt-dlp\plugins\yt-dlp-TTUser\extractor\yt_dlp_plugins
still didn't work :/ 
PS D:\yt-dlp>  .\yt-dlp --extractor-args "tiktok:sec_uid=7275926590302995458" -vU https://www.tiktok.com/@chucker03
[debug] Command-line config: ['--extractor-args', 'tiktok:sec_uid=7275926590302995458', '-vU', 'https://www.tiktok.com/@chucker03']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@chucker03
[tiktok:user] chucker03: Downloading webpage
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] chucker03: Downloading user video list page 1
ERROR: [tiktok:user] chucker03: chucker03: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\tiktok.py", line 806, in _real_extract
  File "yt_dlp\utils\traversal.py", line 239, in traverse_obj
  File "yt_dlp\utils\traversal.py", line 227, in _traverse_obj
  File "yt_dlp\utils\traversal.py", line 215, in apply_path
  File "yt_dlp\utils\traversal.py", line 173, in apply_key
  File "yt_dlp\utils\_utils.py", line 2195, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 774, in _video_entries_api
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\extractor\common.py", line 3760, in _error_or_warning
  File "yt_dlp\utils\_utils.py", line 5122, in report_retry
  File "yt_dlp\extractor\tiktok.py", line 776, in _video_entries_api
  File "yt_dlp\extractor\tiktok.py", line 132, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 125, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 62, in _call_api_impl
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 1039, in download_handle
  File "yt_dlp\extractor\common.py", line 1029, in parse
  File "yt_dlp\extractor\common.py", line 1016, in _parse_json
  File "yt_dlp\extractor\common.py", line 999, in __print_error

  File "yt_dlp\utils\_utils.py", line 555, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1013, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 563, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

**Comment by bashonly** [comment]
Last try:
`C:\Users\zacha\AppData\Roaming\yt-dlp\plugins\yt-dlp-TTUser\yt_dlp_plugins\extractor\tt_user.py`
(you need to flip-flop `extractor` and `yt_dlp_plugins` in the path)

**Comment by Zachary247** [comment]
C:\Users\zacha\AppData\Roaming\yt-dlp\plugins\yt-dlp-TTUser\yt_dlp_plugins\extractor
Nope. It sucks becuase when it was working it was working so well for a week auto scraping my channels but now it doesn't work. I tried making a automated Python, Selenium and BeautifulSoup scrapper with chatgpt but got stuck at the captha part. yt-dlp works so good for downloading single videos but I dont know a way to automate new video links from a channel :/.

Here was the error I got 
Also thank you for your help you have been very kind :) 

PS D:\yt-dlp>  .\yt-dlp --extractor-args "tiktok:sec_uid=7275926590302995458" -vU https://www.tiktok.com/@chucker03
[debug] Command-line config: ['--extractor-args', 'tiktok:sec_uid=7275926590302995458', '-vU', 'https://www.tiktok.com/@chucker03']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Extractor Plugins: TTUser (TikTokUserIE)
[debug] Plugin directories: ['C:\\Users\\zacha\\AppData\\Roaming\\yt-dlp\\plugins\\yt-dlp-TTUser\\yt_dlp_plugins']
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user+TTUser] Extracting URL: https://www.tiktok.com/@chucker03
[download] Downloading playlist: chucker03
[tiktok:user+TTUser] chucker03: Downloading page 1
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\networking\_urllib.py", line 410, in _send
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 415, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4070, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 400: Bad Request

[tiktok:user+TTUser] Playlist chucker03: Downloading 1 items
[download] Finished downloading playlist: chucker03

**Comment by bashonly** [comment]
> ```
> [debug] Extractor Plugins: TTUser (TikTokUserIE)
> [debug] Plugin directories: ['C:\Users\zacha\AppData\Roaming\yt-dlp\plugins\yt-dlp-TTUser\yt_dlp_plugins']
> [tiktok:user+TTUser] Extracting URL: https://www.tiktok.com/@chucker03`
> [download] Downloading playlist: chucker03`
> [tiktok:user+TTUser] chucker03: Downloading page 1
> ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request
> ```

well at least yt-dlp loaded the plugin this time. I can't reproduce this error, so I can't begin to attempt to fix it

**Comment by bashonly** [comment]
@Zachary247 actually, try again without the `--extractor-arg`. I think you are passing the wrong ID

**Comment by Zachary247** [comment]
Hu it works now tried with 3 differnet usernames. But that makes me think why doesn't the --extractor-arg work I got the user ID from following the user and then inspecting  the page. And trying to download the username before adding the plugin wasn't working either.
<a style="text-decoration:none" class="tiktok-22xkqc-StyledLink er1vbsz0" href="/messages?lang=en&amp;u=7275274545622336513"><button type="button" class="e18e4obn3 tiktok-1btqthh-Button-StyledMessageButton ehk74z00">Messages</button></a>
Thanks for your help thou I was just about to cave and buy 4kdownload but u saved me :) thank u

**Comment by bashonly** [comment]
> why doesn't the --extractor-arg work I got the user ID from following the user and then inspecting the page

Because you were passing the wrong ID. The numeric user ID is not the `sec_uid`. 
To get a user's `sec_uid,` you can use `--print channel_id` with one of the user's video URLs, e.g.:
`yt-dlp --print channel_id "https://www.tiktok.com/@chucker03/video/7278873693315517697"`
