### ISSUE TITLE
random 404 error on userchannel.

### ISSUE THREAD

**Issue by Zachary247** [bashonly/yt-dlp-TTUser#6]
Request for a comment. Sometimes randomly I get this on a users channel and it last for like several days. I tested it on other pc and I don't get the error so it is mostlikely a ip block. Whats the best way around this error. I have 5-10 delay for each video and 130s between each username. Will increasing these number prevent the random channel blocks? or is there no way around this? Just posting here becuase Idk were else to ask. What are your guys way around this? adding vpn timer? running 2pc's/virtual machines?

**Comment by bashonly** [comment]
at what point during extraction do you get the error? can you share a verbose log? (add `-v` to your command)

**Comment by Zachary247** [comment]
of course :)

[debug] Command-line config: ['--download-archive', 'Cat1_History.txt', '-v', '--output', 'E:\\TiktokArchive\\Tiktok_Updated_Cat1_Vids\\%(uploader)s aka %(creator)s_%(like_count)sLikes_%(view_count)sViews_url_%(id)s.%(ext)s', '--parse-metadata', 'title:description', '--embed-metadata', '--sleep-interval', '5', '--max-sleep-interval', '10', 'https://www.tiktok.com/@(username1)']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg [6.0-full_build-www.gyan.dev](http://6.0-full_build-www.gyan.dev/) (setts), ffprobe [6.0-full_build-www.gyan.dev](http://6.0-full_build-www.gyan.dev/)
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Extractor Plugins: TTUser (TikTokUserIE)
[debug] Plugin directories: ['C:\\Users\\zacha\\AppData\\Roaming\\yt-dlp\\plugins\\yt-dlp-TTUser\\yt_dlp_plugins']
[debug] Loaded 1890 extractors
[debug] Loading archive file 'Cat1_History.txt'
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user+TTUser] Extracting URL: https://www.tiktok.com/@(username1)
[tiktok:user+TTUser] (username1): Downloading user webpage
[download] Downloading playlist: (username1)
[tiktok:user+TTUser] (username1): Downloading page 1
[tiktok:user+TTUser] (username1): Downloading page 2
[tiktok:user+TTUser] (username1): Downloading page 3
[tiktok:user+TTUser] (username1): Downloading page 4
[tiktok:user+TTUser] (username1): Downloading page 5
[tiktok:user+TTUser] (username1): Downloading page 6
[tiktok:user+TTUser] (username1): Downloading page 7
[tiktok:user+TTUser] (username1): Downloading page 8
[tiktok:user+TTUser] (username1): Downloading page 9
[tiktok:user+TTUser] (username1): Downloading page 10
[tiktok:user+TTUser] (username1): Downloading page 11
[tiktok:user+TTUser] (username1): Downloading page 12
[tiktok:user+TTUser] (username1): Downloading page 13
[tiktok:user+TTUser] (username1): Downloading page 14
[tiktok:user+TTUser] (username1): Downloading page 15
[tiktok:user+TTUser] (username1): Downloading page 16
[tiktok:user+TTUser] (username1): Downloading page 17
[tiktok:user+TTUser] (username1): Downloading page 18
[tiktok:user+TTUser] (username1): Downloading page 19
[tiktok:user+TTUser] (username1): Downloading page 20
[tiktok:user+TTUser] (username1): Downloading page 21
[tiktok:user+TTUser] (username1): Downloading page 22
[tiktok:user+TTUser] (username1): Downloading page 23
[tiktok:user+TTUser] (username1): Downloading page 24
[tiktok:user+TTUser] (username1): Downloading page 25
[tiktok:user+TTUser] (username1): Downloading page 26
[tiktok:user+TTUser] (username1): Downloading page 27
[tiktok:user+TTUser] (username1): Downloading page 28
[tiktok:user+TTUser] (username1): Downloading page 29
[tiktok:user+TTUser] (username1): Downloading page 30
[tiktok:user+TTUser] (username1): Downloading page 31
[tiktok:user+TTUser] (username1): Downloading page 32
[tiktok:user+TTUser] (username1): Downloading page 33
[tiktok:user+TTUser] (username1): Downloading page 34
[tiktok:user+TTUser] (username1): Downloading page 35
[tiktok:user+TTUser] (username1): Downloading page 36
[tiktok:user+TTUser] (username1): Downloading page 37
[tiktok:user+TTUser] (username1): Downloading page 38
[tiktok:user+TTUser] (username1): Downloading page 39
[tiktok:user+TTUser] (username1): Downloading page 40
[tiktok:user+TTUser] (username1): Downloading page 41
[tiktok:user+TTUser] (username1): Downloading page 42
[tiktok:user+TTUser] (username1): Downloading page 43
[tiktok:user+TTUser] (username1): Downloading page 44
[tiktok:user+TTUser] (username1): Downloading page 45
[tiktok:user+TTUser] (username1): Downloading page 46
[tiktok:user+TTUser] (username1): Downloading page 47
[tiktok:user+TTUser] (username1): Downloading page 48
[tiktok:user+TTUser] (username1): Downloading page 49
[tiktok:user+TTUser] (username1): Downloading page 50
[tiktok:user+TTUser] (username1): Downloading page 51
[tiktok:user+TTUser] (username1): Downloading page 52
[tiktok:user+TTUser] (username1): Downloading page 53
[tiktok:user+TTUser] (username1): Downloading page 54
[tiktok:user+TTUser] (username1): Downloading page 55
[tiktok:user+TTUser] (username1): Downloading page 56
[tiktok:user+TTUser] (username1): Downloading page 57
[tiktok:user+TTUser] (username1): Downloading page 58
[tiktok:user+TTUser] (username1): Downloading page 59
[tiktok:user+TTUser] (username1): Downloading page 60
[tiktok:user+TTUser] (username1): Downloading page 61
[tiktok:user+TTUser] (username1): Downloading page 62
[tiktok:user+TTUser] (username1): Downloading page 63
[tiktok:user+TTUser] (username1): Downloading page 64
[tiktok:user+TTUser] (username1): Downloading page 65
[tiktok:user+TTUser] Playlist (username1): Downloading 940 items of 940
[download] 7297306727429524779: has already been recorded in the archive
[download] 7297277515301735723: has already been recorded in the archive
[download] 7297075668179815722: has already been recorded in the archive
[download] 7296537602008632618: has already been recorded in the archive
[download] 7296537496517774638: has already been recorded in the archive
[download] 7296157426078813486: has already been recorded in the archive
[download] 7295872795265764650: has already been recorded in the archive
[download] 7295872673471728942: has already been recorded in the archive
[download] 7295862569363950890: has already been recorded in the archive
[download] 7295186509836111146: has already been recorded in the archive
[download] 7292448883685248302: has already been recorded in the archive
[download] 7292100029446229290: has already been recorded in the archive
[download] 7292099949729254698: has already been recorded in the archive
[download] 7291682815458970923: has already been recorded in the archive
[download] 7291680776616267050: has already been recorded in the archive
[download] 7291360173338217770: has already been recorded in the archive
[download] 7291360098826439979: has already been recorded in the archive
[download] 7291343438597917998: has already been recorded in the archive
[download] 7291079852239621418: has already been recorded in the archive
[download] 7291079517207121195: has already been recorded in the archive
[download] 7291079465587756331: has already been recorded in the archive
[download] 7290669851910180139: has already been recorded in the archive
[download] 7290669589422296363: has already been recorded in the archive
[download] 7290669401244912942: has already been recorded in the archive
[download] 7290299869342747947: has already been recorded in the archive
[download] 7290299802531695915: has already been recorded in the archive
[download] 7289254881108544814: has already been recorded in the archive
[download] 7289254754444725547: has already been recorded in the archive
[download] 7289254594855783726: has already been recorded in the archive
[download] 7288389025231097130: has already been recorded in the archive
[download] 7288388086743010602: has already been recorded in the archive
[download] 7286889988397010219: has already been recorded in the archive
[download] 7286889890913078571: has already been recorded in the archive
[download] 7286889902346603818: has already been recorded in the archive
[download] 7286680830469000494: has already been recorded in the archive
[download] 7286680496870919470: has already been recorded in the archive
[download] 7286205991111118122: has already been recorded in the archive
[download] 7286205392584002859: has already been recorded in the archive
[download] 7285846245749411115: has already been recorded in the archive
[download] 7285846011522682155: has already been recorded in the archive
[download] 7285845981856501038: has already been recorded in the archive
[download] 7280253987696217386: has already been recorded in the archive
[download] 7279838971830603054: has already been recorded in the archive
[download] 7279838241463749930: has already been recorded in the archive
[download] 7279837992238255403: has already been recorded in the archive
[download] 7279558293746502954: has already been recorded in the archive
[download] 7279558234313084206: has already been recorded in the archive
[download] 7277634704449277230: has already been recorded in the archive
[download] 7277634532164160814: has already been recorded in the archive
[download] 7277634381219401002: has already been recorded in the archive
[download] 7276900439440854315: has already been recorded in the archive
[download] 7276900238453935403: has already been recorded in the archive
[download] 7276899844793355562: has already been recorded in the archive
[download] 7276597623203564842: has already been recorded in the archive
[download] 7276594877381545262: has already been recorded in the archive
[download] 7276594758707940650: has already been recorded in the archive
[download] 7272087156397542699: has already been recorded in the archive
[download] 7272085195795352875: has already been recorded in the archive
[download] 7272084793074961706: has already been recorded in the archive
[download] 7271799116324212011: has already been recorded in the archive
[download] 7271777251946024234: has already been recorded in the archive
[download] 7271776442235538731: has already been recorded in the archive
[download] 7270712548402433323: has already been recorded in the archive
[download] 7270712414847552814: has already been recorded in the archive
[download] 7270712208361917738: has already been recorded in the archive
[download] 7270279721743699242: has already been recorded in the archive
[download] 7270279149363727658: has already been recorded in the archive
[download] 7267341494510488878: has already been recorded in the archive
[download] 7267337963644652843: has already been recorded in the archive
[download] 7267336715843489070: has already been recorded in the archive
[download] 7266708290489388331: has already been recorded in the archive
[download] 7266568539677543723: has already been recorded in the archive
[download] 7266568239595949355: has already been recorded in the archive
[download] 7265811075201879339: has already been recorded in the archive
[download] 7265804331566370090: has already been recorded in the archive
[download] 7265802678226210091: has already been recorded in the archive
[download] 7265528746638101803: has already been recorded in the archive
[download] 7265089949026831659: has already been recorded in the archive
[download] 7265089219222359342: has already been recorded in the archive
[download] 7265087680160238894: has already been recorded in the archive
[download] 7264695625885797674: has already been recorded in the archive
[download] 7264695099718733099: has already been recorded in the archive
[download] 7262471730222861610: has already been recorded in the archive
[download] 7262471381567180074: has already been recorded in the archive
[download] 7262470850522139946: has already been recorded in the archive
[download] 7257337688695573803: has already been recorded in the archive
[download] 7257334790666325290: has already been recorded in the archive
[download] 7256974238807018798: has already been recorded in the archive
[download] 7256949873583443242: has already been recorded in the archive
[download] 7255323864954047790: has already been recorded in the archive
[download] 7255323375101513006: has already been recorded in the archive
[download] 7255033435713015083: has already been recorded in the archive
[download] 7255033271522774318: has already been recorded in the archive
[download] 7255032529491741994: has already been recorded in the archive
[download] 7254722656388255019: has already been recorded in the archive
[download] 7254722116073917739: has already been recorded in the archive
[download] 7254721812787973418: has already been recorded in the archive
[download] 7253196653417614635: has already been recorded in the archive
[download] 7253194603468295470: has already been recorded in the archive
[download] 7253192195296005422: has already been recorded in the archive
[download] 7249875441547250990: has already been recorded in the archive
[download] 7248400781219466538: has already been recorded in the archive
[download] 7248399975606996266: has already been recorded in the archive
[download] 7248045688721034542: has already been recorded in the archive
[download] 7248042621535309098: has already been recorded in the archive
[download] 7247773472951389486: has already been recorded in the archive
[download] 7247669035033464110: has already been recorded in the archive
[download] 7247665550942309675: has already been recorded in the archive
[download] 7247664810215673130: has already been recorded in the archive
[download] 7246858934617656622: has already been recorded in the archive
[download] 7246858298429902122: has already been recorded in the archive
[download] 7246858231660743978: has already been recorded in the archive
[download] 7246510579521686827: has already been recorded in the archive
[download] 7246508201410317614: has already been recorded in the archive
[download] 7246506171203439914: has already been recorded in the archive
[download] 7245451807764516142: has already been recorded in the archive
[download] 7244985919969725739: has already been recorded in the archive
[download] 7244985658064817450: has already been recorded in the archive
[download] 7244985490796039466: has already been recorded in the archive
[download] 7244605688276618538: has already been recorded in the archive
[download] 7244603843596520750: has already been recorded in the archive
[download] 7244600052562382123: has already been recorded in the archive
[download] 7244300272359525675: has already been recorded in the archive
[download] 7244299290900745518: has already been recorded in the archive
[download] 7244240408711040298: has already been recorded in the archive
[download] 7243865361987259691: has already been recorded in the archive
[download] 7243857271095217454: has already been recorded in the archive
[download] 7243517023735565614: has already been recorded in the archive
[download] 7243516475330399530: has already been recorded in the archive
[download] 7243128039016582442: has already been recorded in the archive
[download] 7243127979079896363: has already been recorded in the archive
[download] 7242708104356400426: has already been recorded in the archive
[download] 7242707950471613738: has already been recorded in the archive
[download] 7242707903231085867: has already been recorded in the archive
[download] 7242363981367725354: has already been recorded in the archive
[download] 7242362371828845870: has already been recorded in the archive
[download] 7242354384540110123: has already been recorded in the archive
[download] 7241231731439799595: has already been recorded in the archive
[download] Downloading item 139 of 940
[TikTok] Extracting URL: https://www.tiktok.com/@(username1)/video/7239821723829521710
[TikTok] 7239821723829521710: Downloading video feed
WARNING: [TikTok] 7239821723829521710: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7239821723829521710: Downloading webpage
ERROR: [TikTok] 7239821723829521710: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2751, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1076, in raise_no_formats
yt_dlp.utils.ExtractorError: [TikTok] 7239821723829521710: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Not very helpful when my script counts errors and comments the username out of the loop.

**Comment by Zachary247** [comment]
ohhh its cuz it's a tiktok image slide show. How would I update my code to download videos and images in my code? is there a way to only download the last image or first image in the slideshow?

**Comment by bashonly** [comment]
yt-dlp does not support downloading images

you may be able to get the audio by passing `--extractor-args "tiktok:web_fallback"`

**Comment by Zachary247** [comment]
How would I add that to my code:

# Define the location of your yt-dlp executable
$ytDlpPath = "yt-dlp.exe"

# Specify the directory where you want to save the updated videos
$outputDirectory = "E:\TiktokArchive\Tiktok_Updated_Cat1_Vids"

# Create the output directory if it doesn't exist
New-Item -Path $outputDirectory -ItemType Directory -Force

# Define the path to the Cat1_History.txt file
$historyFilePath = "Cat1_History.txt"

# Define the path to the Cat1_User.txt file
$usernamesFilePath = "E:\TiktokArchive\AddUserNamesHereCat1\Cat1_User.txt"


# Read TikTok usernames from the Cat1_User.txt file
$usernames = Get-Content $usernamesFilePath

# Loop through each TikTok username
foreach ($tiktokUsername in $usernames) {
    # Trim leading and trailing whitespace
    $tiktokUsername = $tiktokUsername.Trim()

    # Check if the line is not empty and does not start with "#"
    if (-not [string]::IsNullOrEmpty($tiktokUsername) -and -not $tiktokUsername.StartsWith("#")) {
        # Construct the URL
        $tiktokUrl = "https://www.tiktok.com/@$tiktokUsername"

        # Download videos not in history
        $downloadCmd = "$ytDlpPath --download-archive ""$historyFilePath"" -v --output `"$outputDirectory\%(uploader)s aka %(creator)s_%(like_count)sLikes_%(view_count)sViews_url_%(id)s.%(ext)s`" --parse-metadata ""description:(?s)(?P<meta_comment>.+)"" --embed-metadata --sleep-interval 5 --max-sleep-interval 10 $tiktokUrl"

        # Start the download process and capture the exit code
        $exitCode = (Start-Process -FilePath "cmd.exe" -ArgumentList "/c $downloadCmd" -Wait -PassThru).ExitCode
        

        # Check the exit code, and if it's 1 (indicating a 404 error), add "#" to the username in the file
        if ($exitCode -eq 1) {
            Write-Host "404 Error: $tiktokUsername"
            (Get-Content $usernamesFilePath) | ForEach-Object {
                if ($_ -eq $tiktokUsername) {
                    "#" + $_
                }
                else {
                    $_
                }
            } | Set-Content $usernamesFilePath
        }
        else {
            # Wait for 3 seconds before processing the next username
            Start-Sleep -Seconds 130
        }
    }
    else {
        Write-Host "Skipped: $tiktokUsername"
    }
}

**Comment by bashonly** [comment]
something like this should work

```
    # Download videos not in history
    $downloadCmd = "$ytDlpPath --extractor-args ""tiktok:web_fallback"" --download-archive ""$historyFilePath"" -v --output `"$outputDirectory\%(uploader)s aka %(creator)s_%(like_count)sLikes_%(view_count)sViews_url_%(id)s.%(ext)s`" --parse-metadata ""description:(?s)(?P<meta_comment>.+)"" --embed-metadata --sleep-interval 5 --max-sleep-interval 10 $tiktokUrl"
```

**Comment by Zachary247** [comment]
I will try it out thank you! :)

**Comment by Zachary247** [comment]
That just made it worse and slower. :/

[debug] Extractor Plugins: TTUser (TikTokUserIE)
[debug] Plugin directories: ['C:\\Users\\zacha\\AppData\\Roaming\\yt-dlp\\plugins\\yt-dlp-TTUser\\yt_dlp_plugins']
[debug] Loaded 1890 extractors
[debug] Loading archive file 'NSFW_History.txt'
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user+TTUser] Extracting URL: https://www.tiktok.com/@hnnhxl
[tiktok:user+TTUser] hnnhxl: Downloading user webpage
[download] Downloading playlist: hnnhxl
[tiktok:user+TTUser] hnnhxl: Downloading page 1
[tiktok:user+TTUser] 7297306727429524779: Downloading video feed
[tiktok:user+TTUser] 7297277515301735723: Downloading video feed
[tiktok:user+TTUser] 7297075668179815722: Downloading video feed
[tiktok:user+TTUser] 7296537602008632618: Downloading video feed
[tiktok:user+TTUser] 7296537496517774638: Downloading video feed
[tiktok:user+TTUser] 7296157426078813486: Downloading video feed
[tiktok:user+TTUser] 7295872795265764650: Downloading video feed
[tiktok:user+TTUser] 7295872673471728942: Downloading video feed
[tiktok:user+TTUser] 7295862569363950890: Downloading video feed
[tiktok:user+TTUser] 7295186509836111146: Downloading video feed
[tiktok:user+TTUser] 7292448883685248302: Downloading video feed
[tiktok:user+TTUser] 7292100029446229290: Downloading video feed
[tiktok:user+TTUser] 7292099949729254698: Downloading video feed
[tiktok:user+TTUser] 7291682815458970923: Downloading video feed
[tiktok:user+TTUser] 7291680776616267050: Downloading video feed
[tiktok:user+TTUser] hnnhxl: Downloading page 2
[tiktok:user+TTUser] 7291360173338217770: Downloading video feed
[tiktok:user+TTUser] 7291360098826439979: Downloading video feed
[tiktok:user+TTUser] 7291343438597917998: Downloading video feed
[tiktok:user+TTUser] 7291079852239621418: Downloading video feed
[tiktok:user+TTUser] 7291079517207121195: Downloading video feed
[tiktok:user+TTUser] 7291079465587756331: Downloading video feed
[tiktok:user+TTUser] 7290669851910180139: Downloading video feed
[tiktok:user+TTUser] 7290669589422296363: Downloading video feed
[tiktok:user+TTUser] 7290669401244912942: Downloading video feed
[tiktok:user+TTUser] 7290299869342747947: Downloading video feed
[tiktok:user+TTUser] 7290299802531695915: Downloading video feed
[tiktok:user+TTUser] 7289254881108544814: Downloading video feed
[tiktok:user+TTUser] 7289254754444725547: Downloading video feed
[tiktok:user+TTUser] 7289254594855783726: Downloading video feed
[tiktok:user+TTUser] 7288389025231097130: Downloading video feed
[tiktok:user+TTUser] hnnhxl: Downloading page 3
[tiktok:user+TTUser] 7288388086743010602: Downloading video feed
[tiktok:user+TTUser] 7286889988397010219: Downloading video feed
[tiktok:user+TTUser] 7286889890913078571: Downloading video feed
[tiktok:user+TTUser] 7286889902346603818: Downloading video feed
[tiktok:user+TTUser] 7286680830469000494: Downloading video feed
[tiktok:user+TTUser] 7286680496870919470: Downloading video feed
[tiktok:user+TTUser] 7286205991111118122: Downloading video feed
[tiktok:user+TTUser] 7286205392584002859: Downloading video feed
[tiktok:user+TTUser] 7285846245749411115: Downloading video feed
[tiktok:user+TTUser] 7285846011522682155: Downloading video feed
[tiktok:user+TTUser] 7285845981856501038: Downloading video feed
[tiktok:user+TTUser] 7280253987696217386: Downloading video feed
[tiktok:user+TTUser] 7279838971830603054: Downloading video feed
[tiktok:user+TTUser] 7279838241463749930: Downloading video feed
[tiktok:user+TTUser] 7279837992238255403: Downloading video feed
[tiktok:user+TTUser] hnnhxl: Downloading page 4
[tiktok:user+TTUser] 7279558293746502954: Downloading video feed
[tiktok:user+TTUser] 7279558234313084206: Downloading video feed
[tiktok:user+TTUser] 7277634704449277230: Downloading video feed
[tiktok:user+TTUser] 7277634532164160814: Downloading video feed
[tiktok:user+TTUser] 7277634381219401002: Downloading video feed
[tiktok:user+TTUser] 7276900439440854315: Downloading video feed
[tiktok:user+TTUser] 7276900238453935403: Downloading video feed
[tiktok:user+TTUser] 7276899844793355562: Downloading video feed
[tiktok:user+TTUser] 7276597623203564842: Downloading video feed
[tiktok:user+TTUser] 7276594877381545262: Downloading video feed
[tiktok:user+TTUser] 7276594758707940650: Downloading video feed
[tiktok:user+TTUser] 7272087156397542699: Downloading video feed
[tiktok:user+TTUser] 7272085195795352875: Downloading video feed
[tiktok:user+TTUser] 7272084793074961706: Downloading video feed
[tiktok:user+TTUser] 7271799116324212011: Downloading video feed
[tiktok:user+TTUser] hnnhxl: Downloading page 5
[tiktok:user+TTUser] 7271777251946024234: Downloading video feed
[tiktok:user+TTUser] 7271776442235538731: Downloading video feed
[tiktok:user+TTUser] 7270712548402433323: Downloading video feed
[tiktok:user+TTUser] 7270712414847552814: Downloading video feed
[tiktok:user+TTUser] 7270712208361917738: Downloading video feed
[tiktok:user+TTUser] 7270279721743699242: Downloading video feed
[tiktok:user+TTUser] 7270279149363727658: Downloading video feed
[tiktok:user+TTUser] 7267341494510488878: Downloading video feed
[tiktok:user+TTUser] 7267337963644652843: Downloading video feed
[tiktok:user+TTUser] 7267336715843489070: Downloading video feed
[tiktok:user+TTUser] 7266708290489388331: Downloading video feed
[tiktok:user+TTUser] 7266568539677543723: Downloading video feed
[tiktok:user+TTUser] hnnhxl: Downloading page 6
[tiktok:user+TTUser] 7266568239595949355: Downloading video feed
[tiktok:user+TTUser] 7265811075201879339: Downloading video feed
[tiktok:user+TTUser] 7265804331566370090: Downloading video feed
[tiktok:user+TTUser] 7265802678226210091: Downloading video feed
[tiktok:user+TTUser] 7265528746638101803: Downloading video feed
[tiktok:user+TTUser] 7265089949026831659: Downloading video feed
[tiktok:user+TTUser] 7265089219222359342: Downloading video feed
[tiktok:user+TTUser] 7265087680160238894: Downloading video feed
[tiktok:user+TTUser] 7264695625885797674: Downloading video feed
[tiktok:user+TTUser] 7264695099718733099: Downloading video feed
[tiktok:user+TTUser] 7262471730222861610: Downloading video feed
[tiktok:user+TTUser] 7262471381567180074: Downloading video feed
[tiktok:user+TTUser] 7262470850522139946: Downloading video feed
[tiktok:user+TTUser] 7257337688695573803: Downloading video feed
[tiktok:user+TTUser] 7257334790666325290: Downloading video feed
[tiktok:user+TTUser] hnnhxl: Downloading page 7
[tiktok:user+TTUser] 7256974238807018798: Downloading video feed
[tiktok:user+TTUser] 7256949873583443242: Downloading video feed
[tiktok:user+TTUser] 7255323864954047790: Downloading video feed
[tiktok:user+TTUser] 7255323375101513006: Downloading video feed
[tiktok:user+TTUser] 7255033435713015083: Downloading video feed
[tiktok:user+TTUser] 7255033271522774318: Downloading video feed
[tiktok:user+TTUser] 7255032529491741994: Downloading video feed
[tiktok:user+TTUser] 7254722656388255019: Downloading video feed
[tiktok:user+TTUser] 7254722116073917739: Downloading video feed
[tiktok:user+TTUser] 7254721812787973418: Downloading video feed
[tiktok:user+TTUser] 7253196653417614635: Downloading video feed
[tiktok:user+TTUser] 7253194603468295470: Downloading video feed
[tiktok:user+TTUser] 7253192195296005422: Downloading video feed
[tiktok:user+TTUser] hnnhxl: Downloading page 8
[tiktok:user+TTUser] 7249875441547250990: Downloading video feed
[tiktok:user+TTUser] 7248400781219466538: Downloading video feed
[tiktok:user+TTUser] 7248399975606996266: Downloading video feed
WARNING: [tiktok:user+TTUser] Unable to find video in feed. Failed to extract from feed; falling back to web API response
[tiktok:user+TTUser] 7248045688721034542: Downloading video feed
[tiktok:user+TTUser] 7248042621535309098: Downloading video feed
[tiktok:user+TTUser] 7247773472951389486: Downloading video feed
[tiktok:user+TTUser] 7247669035033464110: Downloading video feed
[tiktok:user+TTUser] 7247665550942309675: Downloading video feed
[tiktok:user+TTUser] 7247664810215673130: Downloading video feed
[tiktok:user+TTUser] 7246858934617656622: Downloading video feed
[tiktok:user+TTUser] 7246858298429902122: Downloading video feed
[tiktok:user+TTUser] 7246858231660743978: Downloading video feed
[tiktok:user+TTUser] 7246510579521686827: Downloading video feed
WARNING: [tiktok:user+TTUser] Unable to find video in feed. Failed to extract from feed; falling back to web API response
[tiktok:user+TTUser] 7246508201410317614: Downloading video feed
[tiktok:user+TTUser] 7246506171203439914: Downloading video feed
[tiktok:user+TTUser] hnnhxl: Downloading page 9
[tiktok:user+TTUser] 7245451807764516142: Downloading video feed
[tiktok:user+TTUser] 7244985919969725739: Downloading video feed
[tiktok:user+TTUser] 7244985658064817450: Downloading video feed
[tiktok:user+TTUser] 7244985490796039466: Downloading video feed
[tiktok:user+TTUser] 7244605688276618538: Downloading video feed
[tiktok:user+TTUser] 7244603843596520750: Downloading video feed

**Comment by bashonly** [comment]
> WARNING: [tiktok:user+TTUser] Unable to find video in feed. Failed to extract from feed; falling back to web API response

this means it is still being downloaded, instead of completely failing (like without the `--extractor-arg`)

it is slower though. what could help is adding `--lazy-playlist --break-on-reject --break-per-input` if you are using a download archive

**Comment by Zachary247** [comment]
Thanks. I found a way around to just to maunally add the id to the archive list 7239821723829521710 then on the next loop it wont run into a error becuase it thinks its been downloaded. It can take sometime depending on how many slideshows on the creators feed. But it does increase preformance and saves time in the long run.
